[project]
name = "jev"
version = "0.1.0"
description = "Local implementation of local JEV like models"
readme = "README.md"
authors = [
    { name = "vince", email = "vince.ajello@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=3.0.0",
    "laya>=0.3.5",
    "peft>=0.17.1",
    "scipy>=1.11.0",
    "transformers>=5.2.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
